# .github/workflows/deploy.yml

name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 如果您需要更细致的权限控制或针对 pull request 的操作，可以取消注释并调整这里的 permissions:
    # permissions:
    #   contents: read
    #   pull-requests: write # 例如，如果部署预览频道并需要在PR中留言

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 您在之前的代码中使用了 22
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0 # <--- 这是主要的更新点
        with:
          version: 8 # 指定您希望使用的 pnpm 版本

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_E50914 }}
          projectId: e50914 # 您的 Firebase 项目 ID
          # 如果您希望部署到预览频道或有更复杂的频道逻辑，可以修改这里的 channelId
          # 例如: channelId: ${{ github.event_name == 'pull_request' && format('pr-{0}-7d', github.event.number) || 'live' }}
          channelId: live # 当前固定部署到 live 频道