name: Deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          # 直接导出认证相关环境变量，简化后续步骤
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # 已由认证步骤导出凭据与项目，无需额外诊断与 project 设置

      # 配置 Artifact Registry 登录
      - name: Configure Artifact Registry auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 本地构建并推送镜像，避免 Cloud Build 依赖 cloudbuild 桶权限
      - name: Docker build and push
        run: |-
          IMAGE="us-central1-docker.pkg.dev/future-spot/cloud-run-source-deploy/color-palette:github-${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      # 部署步骤：服务名改为 color-palette
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy color-palette \
            --project future-spot \
            --image us-central1-docker.pkg.dev/future-spot/cloud-run-source-deploy/color-palette:github-${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account 945611373934-compute@developer.gserviceaccount.com
