# .github/workflows/deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 
          cache: 'pnpm' # 这个缓存是为pnpm的全局存储，而不是pnpm本身

      # 移除以下两步:
      # - name: Enable corepack
      #   run: corepack enable
      # - name: Prepare and activate pnpm
      #   run: corepack prepare pnpm@8 --activate

      # 重新添加 pnpm/action-setup 步骤:
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # 您可以使用 v3 或查找是否有更新的 v4 版本
        with:
          version: 8 # 指定您希望使用的 pnpm 版本

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_E50914 }}
          projectId: e50914
          channelId: live